CREATE TABLE IF NOT EXISTS FOO_SEQUENCES (
FULL_TABLE_NAME varchar(513)  PRIMARY KEY NOT NULL,
HOST 			varchar(1000) NOT NULL,
SCHEMA_NAME 	varchar(256)  NOT NULL,
TABLE_NAME		varchar(256)  NOT NULL,
OFFSET 			int 		  NOT NULL,
INCREMENT_BY 	int           NOT NULL,
AUTO_INCREMENT 	int           NOT NULL
);