CREATE PROCEDURE IF NOT EXISTS SET_AUTO_INCREMENT_WITH_INNER_TX(P_SCHEMA2 VARCHAR(256), P_TABLE_NAME VARCHAR(256), P_ROW_CNT INTEGER)
BEGIN

DECLARE V_FULL_TABLE_NAME VARCHAR(513);
DECLARE V_CURRENT_AUTO_INCREMENT INT;

DECLARE V_AUTO_INCREMENT INT;
DECLARE V_OFFSET INT;
DECLARE V_INCREMENT_BY INT;

/*SET @@SESSION.INFORMATION_SCHEMA_STATS_EXPIRY = 0;*/ /* ONLY VER 8.X MYSQL */

SET V_FULL_TABLE_NAME = CONCAT(P_SCHEMA, '.', P_TABLE_NAME);

START TRANSACTION;

SELECT AUTO_INCREMENT
INTO  V_CURRENT_AUTO_INCREMENT
FROM FOO_SEQUENCES
WHERE FULL_TABLE_NAME = V_FULL_TABLE_NAME
FOR UPDATE;

UPDATE FOO_SEQUENCES
SET AUTO_INCREMENT = AUTO_INCREMENT + (P_ROW_CNT * @@SESSION.AUTO_INCREMENT_INCREMENT)
WHERE FULL_TABLE_NAME = V_FULL_TABLE_NAME;

/*MODULO*/
SELECT AUTO_INCREMENT, OFFSET, INCREMENT_BY
INTO V_AUTO_INCREMENT, V_OFFSET, V_INCREMENT_BY
FROM FOO_SEQUENCES
WHERE FULL_TABLE_NAME = V_FULL_TABLE_NAME;

COMMIT;

/*TODO ROLLBACK ON EXCEPTION AND THROW EXCEPTION*/
SELECT V_AUTO_INCREMENT, V_OFFSET, V_INCREMENT_BY;

END
