// Package reservationdb owns isolated live MySQL/PostgreSQL acceptance fixtures.
// It never substitutes another product when a requested server is unavailable.
package reservationdb

import (
	"context"
	"crypto/rand"
	"database/sql"
	"encoding/hex"
	"fmt"
	"os"
	"testing"
	"time"

	_ "github.com/go-sql-driver/mysql"
	_ "github.com/lib/pq"
	_ "github.com/viant/sqlx/metadata/product/mysql"
	mysqlsequence "github.com/viant/sqlx/metadata/product/mysql/sequence"
	_ "github.com/viant/sqlx/metadata/product/pg"
)

type Database struct {
	DB                  *sql.DB
	Driver, DSN, Schema string
}

func Open(t testing.TB, driver string) *Database { return open(t, driver, true) }

// OpenTransient creates source fixtures without provisioning an allocator table.
func OpenTransient(t testing.TB) *Database { return open(t, "mysql", false) }

func open(t testing.TB, driver string, provision bool) *Database {
	t.Helper()
	env := "F1_MYSQL_DSN"
	if driver == "postgres" {
		env = "F1_POSTGRES_DSN"
	}
	dsn := os.Getenv(env)
	if dsn == "" {
		if os.Getenv("F1_REQUIRE_LIVE") == "1" {
			t.Fatalf("required live acceptance missing %s", env)
		}
		t.Skip(env + " absent; live acceptance NOT executed")
	}
	db, err := sql.Open(driver, dsn)
	if err != nil {
		t.Fatal(err)
	}
	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()
	if err = db.PingContext(ctx); err != nil {
		db.Close()
		t.Fatal(err)
	}
	var token [8]byte
	if _, err = rand.Read(token[:]); err != nil {
		t.Fatal(err)
	}
	h := &Database{DB: db, Driver: driver, DSN: dsn, Schema: "f1_" + hex.EncodeToString(token[:])}
	if driver == "mysql" {
		if provision {
			if err = (&mysqlsequence.Store{}).Install(ctx, db); err != nil {
				db.Close()
				t.Fatal(err)
			}
		}
		_, err = db.ExecContext(ctx, "CREATE DATABASE "+h.Quote(h.Schema))
	} else {
		_, err = db.ExecContext(ctx, "CREATE SCHEMA "+h.Quote(h.Schema))
	}
	if err != nil {
		db.Close()
		t.Fatal(err)
	}
	t.Cleanup(func() {
		cleanup, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()
		if driver == "mysql" {
			_, _ = db.ExecContext(cleanup, "DELETE FROM sqlx_allocator.sequence_reservations WHERE table_schema=?", h.Schema)
			_, _ = db.ExecContext(cleanup, "DROP DATABASE "+h.Quote(h.Schema))
		} else {
			_, _ = db.ExecContext(cleanup, "DROP SCHEMA "+h.Quote(h.Schema)+" CASCADE")
		}
		_ = db.Close()
	})
	return h
}
func (h *Database) Quote(name string) string {
	if h.Driver == "mysql" {
		return "`" + name + "`"
	}
	return `"` + name + `"`
}
func (h *Database) Table(name string) string { return h.Quote(h.Schema) + "." + h.Quote(name) }
func (h *Database) Exec(t testing.TB, statements ...string) {
	t.Helper()
	for _, stmt := range statements {
		if _, err := h.DB.ExecContext(context.Background(), stmt); err != nil {
			t.Fatalf("fixture SQL %s: %v", stmt, err)
		}
	}
}
func (h *Database) Other(t testing.TB) *sql.DB {
	t.Helper()
	db, err := sql.Open(h.Driver, h.DSN)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = db.Close() })
	return db
}
func (h *Database) CreateRecords(t testing.TB) {
	t.Helper()
	if h.Driver == "mysql" {
		h.Exec(t, "CREATE TABLE "+h.Table("records")+" (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,name VARCHAR(64) NOT NULL) ENGINE=InnoDB")
	} else {
		h.Exec(t, "CREATE TABLE "+h.Table("records")+" (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT NOT NULL)")
	}
}
func (h *Database) Count(t testing.TB, table string) int {
	t.Helper()
	var count int
	if err := h.DB.QueryRow("SELECT count(*) FROM " + h.Table(table)).Scan(&count); err != nil {
		t.Fatal(err)
	}
	return count
}
func (h *Database) SeedIDSQL(id int64) string {
	return fmt.Sprintf("INSERT INTO %s(id,name) VALUES(%d,'seed')", h.Table("records"), id)
}

// Join connects a subprocess to its parent's already-created fixture objects.
func Join(t testing.TB, driver string) *Database {
	t.Helper()
	env := "F1_MYSQL_DSN"
	if driver == "postgres" {
		env = "F1_POSTGRES_DSN"
	}
	dsn := os.Getenv(env)
	if dsn == "" {
		t.Fatalf("subprocess missing %s", env)
	}
	db, err := sql.Open(driver, dsn)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = db.Close() })
	return &Database{DB: db, Driver: driver, DSN: dsn}
}
